name: Run Racket E-Commerce App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Racket
    - name: Install Racket
      run: |
        sudo add-apt-repository ppa:plt/racket
        sudo apt-get update
        sudo apt-get install -y racket

    # Run the Racket web server in the background
    - name: Run Racket E-Commerce App
      run: |
        racket racket-ecommerce-app.rkt &
        sleep 20  # Increased sleep time to 20 seconds to allow the server to start

    # Test the web server using curl
    - name: Test Web Server
      run: |
        curl http://0.0.0.0:8080 | grep "Welcome to the Racket E-Commerce App"
        curl "http://0.0.0.0:8080?add=1"  # Add a product to the cart
        curl "http://0.0.0.0:8080?remove=1"  # Remove a product from the cart

    # Keep the server running for 60 seconds (optional)
    - name: Sleep for 60 seconds
      run: sleep 60
