name: Run Racket E-Commerce Web Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Racket
    - name: Install Racket
      run: |
        sudo add-apt-repository ppa:plt/racket
        sudo apt-get update
        sudo apt-get install -y racket

    # Run the Racket web server
    - name: Run E-Commerce Web Server
      run: |
        racket ecommerce-app.rkt &

    # Test the web server using curl
    - name: Test Web Server
      run: |
        sleep 5  # Wait for server to start
        curl http://localhost:8080
        curl "http://localhost:8080?add=1"
        curl "http://localhost:8080?remove=1"
        
    # Keep the server running for 60 seconds (to allow manual inspection if needed)
    - name: Sleep for 60 seconds
      run: sleep 60
